### ISSUE TITLE
No styles?

### ISSUE THREAD

**Issue by nrei0** [jluccisano/webpack-es6-boilerplate#1]
Hello. I found this boilerplate when goes around the internet, but I were a little bit confused about missed styles loader. So I need manually to install styles preprocessors to deal with it, otherwise boilerplate not works for me.

Will be better to set postcss (autoprefixer) and scss loaders, because commonly if you are working with html, you also works with css too, then it will be boilerplate.

Thanks!

**Comment by jluccisano** [comment]
Hello,
You can see the active branch "react-sass-webpack-es6-boilerplate"

**Comment by nrei0** [comment]
Sure, thanks, but repository called as "webpack-es6-boilerplate" which determines do no use of react.

So my case to make html5 banner and I want to have all stuff already set up, but without libraries such as react and settings which reflects to bundle.

**Comment by jluccisano** [comment]
Yes You're right, I'm going to make the fix.

**Comment by jluccisano** [comment]
#143f225d364fe249736c019e50043c05252bfdc0

**Comment by jluccisano** [comment]
merged on master.
